# Generated by Django 4.1.3 on 2022-11-28 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0002_alter_documents_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documents",
            name="author",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author_document",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="documents",
            name="date_create",
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name="documents",
            name="file",
            field=models.FileField(
                blank=True, upload_to="documents/%Y/%m/%d/", verbose_name="Файл"
            ),
        ),
        migrations.AlterField(
            model_name="documents",
            name="number",
            field=models.IntegerField(blank=True, verbose_name="Номер"),
        ),
        migrations.AlterField(
            model_name="documents",
            name="title",
            field=models.CharField(blank=True, max_length=500, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="documents",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="type_document",
                to="main.type",
                verbose_name="Тип документа",
            ),
        ),
    ]
