# Generated by Django 4.1.3 on 2022-11-28 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_documents_author_alter_documents_date_create_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documents", name="date_create", field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="documents",
            name="file",
            field=models.FileField(
                upload_to="documents/%Y/%m/%d/", verbose_name="Файл"
            ),
        ),
        migrations.AlterField(
            model_name="documents",
            name="number",
            field=models.IntegerField(verbose_name="Номер"),
        ),
        migrations.AlterField(
            model_name="documents",
            name="title",
            field=models.CharField(max_length=500, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="documents",
            name="type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="type_document",
                to="main.type",
                verbose_name="Тип документа",
            ),
        ),
    ]
