# Generated by Django 4.1.3 on 2022-11-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_documents_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documents",
            name="number",
            field=models.IntegerField(null=True, verbose_name="Номер"),
        ),
    ]
