# Generated by Django 4.1.3 on 2022-11-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_documents_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documents",
            name="date_create",
            field=models.DateField(null=True),
        ),
    ]
