# Generated by Django 4.1.3 on 2022-11-28 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0008_alter_documents_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documents",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author_document",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
