# Generated by Django 4.1.3 on 2022-12-05 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_favorites"),
    ]

    operations = [
        migrations.RenameField(
            model_name="favorites", old_name="book", new_name="document",
        ),
    ]
