# Generated by Django 4.1.3 on 2022-12-15 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_executor_documents_executor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documents",
            name="date_create",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="documents",
            name="file",
            field=models.FileField(
                blank=True, upload_to="documents/%Y/%m/%d/", verbose_name="Файл"
            ),
        ),
        migrations.AlterField(
            model_name="documents",
            name="number",
            field=models.IntegerField(blank=True, null=True, verbose_name="Номер"),
        ),
        migrations.AlterField(
            model_name="documents",
            name="title",
            field=models.CharField(blank=True, max_length=500, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="documents",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="type_document",
                to="main.type",
                verbose_name="Тип документа",
            ),
        ),
    ]
