# Generated by Django 4.1.3 on 2022-12-15 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0015_alter_documents_date_create_alter_documents_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documents",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author_document",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="documents",
            name="date_create",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="documents",
            name="file",
            field=models.FileField(
                upload_to="documents/%Y/%m/%d/", verbose_name="Файл"
            ),
        ),
        migrations.AlterField(
            model_name="documents",
            name="number",
            field=models.IntegerField(null=True, verbose_name="Номер"),
        ),
        migrations.AlterField(
            model_name="documents",
            name="title",
            field=models.CharField(max_length=500, verbose_name="Название"),
        ),
    ]
