# Generated by Django 4.1.3 on 2022-12-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_alter_documents_author_alter_documents_date_create_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documents",
            name="file",
            field=models.FileField(upload_to="documents/%Y/%m/%d/"),
        ),
    ]
